ABEND = "/x"
ACCESS_KEYWORD ="ACCESS"
ADDITION_OPERATOR = "+"
ADDRESS_INDICATOR = "&&*"
ADDRESS_KEYWORD = "ADDRESS"
ADDRESS_OF_PREFIX = "_addr_"
ALL_KEYWORD ="ALL"
ALTER_KEYWORD = "ALTER"
ALPHANUMERIC_DATA_TYPE = "X"
ALSO_KEYWORD = "ALSO"
AND_KEYWORD = "AND"
ASSIGN_KEYWORD ="ASSIGN"
AT_KEYWORD = "AT"
BASE_LEVEL = 3
BINARY_KEYWORD = "BINARY"
BY_KEYWORD = "BY"
CALLING_MODULE_MEMBER = "calling_module"
CICS_KEYWORD = "CICS"
CLASS_ERROR_FUNCTION_MEMBER = "error_func"
CLASS_KEYWORD = "CLASS"
CLOSE_BRACKET = ']'
CLOSE_PARENS = ")"
COBOL_COMMENT = "*"
COBOL_CONTINUATION_CHAR = "-"
COBOL_RETURN_KEYWORD = "RETURN"
COLON = ":"
COMMA = ","
COMMAREA_KEYWORD = "COMMAREA"
COMP_KEYWORD = "COMP"
COMP_1_KEYWORD = "COMP-1"
COMP_2_KEYWORD = "COMP-2"
COMP_3_KEYWORD = "COMP-3"
COMP_4_KEYWORD = "COMP-4"
COMP_5_KEYWORD = "COMP-5"
CONFIGURATION_SECTION =  "CONFIGURATION SECTION."
CONSOLE_KEYWORD = "CONSOLE"
CONTENT_KEYWORD = "CONTENT"
CONVERTING_KEYWORD = "CONVERTING"
COPYBOOK_EXT = ".CPY"
COPYBOOK_FOLDER = "copybooks/"
COPYBOOK_KEYWORD = "COPY"
DASH = "-"
DATA_DIVISION_POS = 3
DD_NAME_LIST = "dd_name_list"
DECIMAL_INDICATOR = "V"
DEF_KEYWORD = "def"
DELIMITED_KEYWORD = "DELIMITED"
DEPENDING_KEYWORD = "DEPENDING"
DESCENDING_KEYWORD = "DESCENDING"
DIVISION_OPERATOR = "/"
DOUBLE_EQUALS = "=="
DOUBLE_QUOTE = "\""
EIB_COPYBOOK = "EIB"
EIB_MEMORY = "EIBMemory"
EIB_VARIABLE_LIST = "EIBList"
ELSE = "else"
EMPTY_STRING = ""
END_KEYWORD = "END"
END_OF_PAGE_KEYWORD = "END-OF-PAGE"
END_RETURN_KEYWORD = "END-RETURN"
ENTRY_KEYWORD = "ENTRY"
ENVIRONMENT_DIVISION_POS = 2
EOP_KEYWORD = "EOP"
EQUAL_KEYWORD = "EQUAL"
EQUALS = "="
EXCEPTION_KEYWORD = "EXCEPTION"
EXEC_KEYWORD = "EXEC"
FALSE_KEYWORD = "FALSE"
FD_KEYWORD = "FD"
FILE_CONTROL_SECTION = "FILE-CONTROL."
FILE_KEYWORD = "FILE"
FILE_STATUS_KEYWORD = "FILE STATUS"
FIRST_KEYWORD = "FIRST"
FROM_KEYWORD = "FROM"
FUNCTION_KEYWORD = "FUNCTION"
GIVING_KEYWORD = "GIVING"
GREATER_KEYWORD = "GREATER"
GREATER_THAN = ">"
GREATER_THAN_EQUAL_TO = ">="
HANDLE_KEYWORD = "HANDLE"
HEX_PREFIX = "_hex_"
HIGH_VALUES_KEYWORD = "HIGH-VALUES"
IDENTIFICATION_DIVISION_NAME = "IDENTIFICATION DIVISION"
IDENTIFICATION_DIVISION_POS = 0
ID_DIVISION_POS = 1
IN_KEYWORD = "in"
INPUT_KEYWORD = "INPUT"
INDENT = "    "
INDEXED_CLAUSE = "INDEXED"
INPUT_OUTPUT_SECTION = "INPUT-OUTPUT SECTION."
INTO_KEYWORD = "INTO"
INVALID_KEYWORD = "INVALID"
IS_KEYWORD ="IS"
JOB_NAME_MEMBER = "job_name"
JOB_STEP_MEMBER = "job_step"
KEY_KEYWORD = "KEY"
LABEL_KEYWORD = "LABEL"
LENGTH_KEYWORD = "LENGTH"
LESS_THAN = "<"
LESS_THAN_EQUAL_TO = "<="
LINE_KEYWORD = "LINE"
LINES_AHEAD = 30
LITERAL = "literal"
LOW_VALUES_KEYWORD = "LOW-VALUES"
MAIN_ARG_VARIABLE_PREFIX = "_arg"
MAIN_ERROR_FUNCTION = "_error_handler"
MEMORY = "Memory"
MINUS_SIGN = "-"
MULTIPLICATION_OPERATOR = "*"
NEGATIVE_KEYWORD = "NEGATIVE"
NEWLINE = "\n"
NEG_ONE = -1
NONE_KEYWORD = "None"
NOT_EQUALS = "!="
NOT_KEYWORD = "NOT"
NUMERIC_KEYWORD = "NUMERIC"
NUMERIC_DATATYPE = "9"
NUMERIC_SIGNED_DATATYPE = "S9"
OCCURS_CLAUSE = "OCCURS"
OF_KEYWORD = "OF"
OPEN_BRACKET = "["
OPEN_PARENS = "("
OR_KEYWORD = "OR"
ORGANIZATION_KEYWORD = "ORGANIZATION"
ORGANISATION_KEYWORD ="ORGANISATION"
OUTPUT_KEYWORD = "OUTPUT"
OVERFLOW_KEYWORD = "OVERFLOW"
PERIOD = "."
PIC_CLAUSE = "PIC"
PLUS_SIGN = "+"
POINTER_CLAUSE = "POINTER"
POINTER_DATATYPE = "P"
PROCEDURE_DIVISION_NAME = "PROCEDURE DIVISION"
PROCEDURE_DIVISION_POS = 4
PROCEDURE_KEYWORD = "PROCEDURE"
PROGRAM_KEYWORD = "PROGRAM"
PYTHON_EXCEPT_STATEMENT = "except Exception as e:"
PYTHON_EXT = ".py"
PYTHON_TRY_STATEMENT = "try:"
RECORD_KEYWORD ="RECORD"
RECORD_KEY_KEYWORD = "RECORD KEY"
REDEFINES_KEYWORD = "REDEFINES"
REMAINDER_KEYWORD = "REMAINDER"
REPLACING_DELIMITER = "=="
REPLACING_KEYWORD = "REPLACING"
RETURN_CONTROL_METHOD = "receive_control()"
RETURN_KEYWORD = "return"
RUN_KEYWORD = "RUN"
SD_KEYWORD = "SD"
SELECT_KEYWORD = "SELECT"
SELF_REFERENCE = "self."
SINGLE_QUOTE = "'"
SIZE_KEYWORD = "SIZE"
SORT_IDENTIFIER = "___sd"
SPACE = " "
SPACE_KEYWORD = "SPACE"
SPACES_KEYWORD = "SPACES"
SPACES_INITIALIZER = "____spaces"
SPECIAL_NAMES_SECTION = "SPECIAL-NAMES."
STATUS_KEYWORD ="STATUS"
STOP_KEYWORD = "STOP"
SUBTRACTION_OPERATOR = "-"
THAN_KEYWORD = "THAN"
THROUGH_KEYWORD = "THROUGH"
THRU_KEYWORD = "THRU"
TIMES_KEYWORD = "TIMES"
TO_KEYWORD = "TO"
TRUE_KEYWORD = "TRUE"
UNDERSCORE = "_"
UNTIL_KEYWORD = "UNTIL"
UPON_KEYWORD = "UPON"
USING_KEYWORD = "USING"
VALUE_CLAUSE = "VALUE"
VARIABLES_LIST_NAME = "variables_list"
VARYING_KEYWORD = "VARYING"
VERB_RESET = "verb__reset"
WHEN_OTHER_KEYWORD = "OTHER"
ZERO = "0"
ZERO_KEYWORD = "ZERO"

ASSEMBLER_FAKE_VERB_GET_DD = "GET_DD_VALUE"

CICS_VERB_ASKTIME = "EXEC CICS ASKTIME"
CICS_VERB_HANDLE = "EXEC CICS HANDLE"
CICS_VERB_HANDLE_ABEND = "EXEC CICS HANDLE ABEND"
CICS_VERB_LINK = "EXEC CICS LINK"
CICS_VERB_RETURN = "EXEC CICS RETURN"
CICS_VERB_SEND = "EXEC CICS SEND"
CICS_VERB_XCTL = "EXEC CICS XCTL"

COBOL_VERB_ACCEPT = "ACCEPT"
COBOL_VERB_ADD = "ADD"
COBOL_VERB_CALL = "CALL"
COBOL_VERB_CLOSE = "CLOSE"
COBOL_VERB_COMPUTE = "COMPUTE"
COBOL_VERB_CONTINUE = "CONTINUE"
COBOL_VERB_DISPLAY = "DISPLAY"
COBOL_VERB_DIVIDE = "DIVIDE"
COBOL_VERB_ELSE = "ELSE"
COBOL_VERB_EVALUATE = "EVALUATE"
COBOL_VERB_EVALUATE_END = "END-EVALUATE"
COBOL_VERB_EXEC_END = "END-EXEC"
COBOL_VERB_EXIT = "EXIT"
COBOL_VERB_GO = "GO"
COBOL_VERB_GOBACK = "GOBACK"
COBOL_VERB_IF = "IF"
COBOL_VERB_IF_END = "END-IF"
COBOL_VERB_INITIALIZE = "INITIALIZE"
COBOL_VERB_INSPECT = "INSPECT"
COBOL_VERB_MOVE = "MOVE"
COBOL_VERB_MULTIPLY = "MULTIPLY"
COBOL_VERB_NEXT = "NEXT"
COBOL_VERB_OPEN = "OPEN"
COBOL_VERB_PERFORM = "PERFORM"
COBOL_VERB_PERFORM_END = "END-PERFORM"
COBOL_VERB_READ = "READ"
COBOL_VERB_READ_END = "END-READ"
COBOL_VERB_RELEASE = "RELEASE"
COBOL_VERB_SEARCH = "SEARCH"
COBOL_VERB_SEARCH_END = "END-SEARCH"
COBOL_VERB_SET = "SET"
COBOL_VERB_SORT = "SORT"
COBOL_VERB_STOPRUN = "STOP RUN"
COBOL_VERB_STOP = "STOP"
COBOL_VERB_STRING = "STRING"
COBOL_VERB_SUBTRACT = "SUBTRACT"
COBOL_VERB_WHEN = "WHEN"
COBOL_VERB_WRITE = "WRITE"

COBOL_VERB_LIST = [
    COBOL_VERB_ADD,
    COBOL_VERB_CALL,
    COBOL_VERB_DISPLAY,
    COBOL_VERB_GOBACK,
    COBOL_VERB_MOVE,
    COBOL_VERB_STOPRUN,
    COBOL_VERB_PERFORM,
    COBOL_VERB_PERFORM_END,
    COBOL_VERB_IF,
    COBOL_VERB_IF_END,
    COBOL_VERB_EXIT,
    COBOL_VERB_ELSE,
    COBOL_VERB_WHEN,
    COBOL_VERB_INSPECT,
    COBOL_VERB_EVALUATE,
    COBOL_VERB_EVALUATE_END,
    COBOL_VERB_CONTINUE,
    COBOL_VERB_OPEN,
    COBOL_VERB_CLOSE,
    COBOL_VERB_READ,
    COBOL_VERB_READ_END,
    COBOL_VERB_WRITE,
    COBOL_VERB_SEARCH,
    COBOL_VERB_SEARCH_END,
    COBOL_VERB_SET,
    COBOL_VERB_STOP,
    COBOL_VERB_SUBTRACT,
    COBOL_VERB_MULTIPLY,
    COBOL_VERB_DIVIDE,
    COBOL_VERB_COMPUTE,
    COBOL_VERB_ACCEPT,
    EXEC_KEYWORD,
    COBOL_VERB_INITIALIZE,
    COBOL_VERB_EXEC_END,
    COBOL_VERB_GO,
    COBOL_VERB_NEXT,
    CICS_VERB_RETURN,
    COBOL_VERB_STRING,
    COBOL_VERB_SORT,
    COBOL_VERB_RELEASE,
    END_RETURN_KEYWORD,
    ASSEMBLER_FAKE_VERB_GET_DD
]

COBOL_BOOLEAN_KEYWORDS = [
    OR_KEYWORD
    , AND_KEYWORD
]

COBOL_END_BLOCK_VERBS = [
    COBOL_VERB_PERFORM_END
    , COBOL_VERB_IF_END
    , COBOL_VERB_EVALUATE_END
    , COBOL_VERB_READ_END
    , COBOL_VERB_SEARCH_END
    , COBOL_VERB_EXEC_END
]

COBOL_VERB_MULTI_LIST = [
    [COBOL_VERB_SEARCH, COBOL_VERB_WHEN]
    , [COBOL_VERB_SEARCH, COBOL_VERB_SET]
    , [COBOL_RETURN_KEYWORD, COBOL_VERB_SET]
    , [COBOL_RETURN_KEYWORD, '!' + COBOL_VERB_SET]
]

COBOL_IDENTIFICATION_DIVISION_VERBS = [
    "PROGRAM-ID."
]

COBOL_DIVISIONS = [
    "IDENTIFICATION DIVISION"
    , "ID DIVISION"
    , "ENVIRONMENT DIVISION"
    , "DATA DIVISION"
    , "PROCEDURE DIVISION"
]

ENVIRONMENT_DIVISION_SECTIONS = [
    FILE_CONTROL_SECTION
    , CONFIGURATION_SECTION
]

DATA_DIVISION_SECTIONS = [
    "WORKING-STORAGE SECTION."
    , "LOCAL-STORAGE SECTION."
    , "LINKAGE SECTION."
    , "FILE SECTION."
]

WORKING_STORAGE_LEVELS = [
    "01"
    , "02"
    , "03"
    , "04"
    , "05"
    , "06"
    , "07"
    , "08"
    , "09"
    , "10"
    , "11"
    , "12"
    , "13"
    , "14"
    , "15"
    , "16"
    , "17"
    , "18"
    , "19"
    , "20"
    , "21"
    , "22"
    , "23"
    , "24"
    , "25"
    , "26"
    , "27"
    , "28"
    , "29"
    , "30"
    , "31"
    , "32"
    , "33"
    , "34"
    , "35"
    , "36"
    , "37"
    , "38"
    , "39"
    , "40"
    , "41"
    , "42"
    , "43"
    , "44"
    , "45"
    , "46"
    , "47"
    , "48"
    , "49"
    , "77"
    , "88"
]

COMP_FIELD_TYPES = [
    COMP_KEYWORD
    , COMP_1_KEYWORD
    , COMP_2_KEYWORD
    , COMP_3_KEYWORD
    , COMP_4_KEYWORD
    , COMP_5_KEYWORD
]

COBOL_COMPARISON_OPERATORS = [
    EQUALS
    , LESS_THAN
    , GREATER_THAN
    , LESS_THAN_EQUAL_TO
    , GREATER_THAN_EQUAL_TO
    , EQUAL_KEYWORD
    , GREATER_KEYWORD
]

COBOL_ARITHMATIC_OPERATORS = [
    ADDITION_OPERATOR,
    SUBTRACTION_OPERATOR,
    MULTIPLICATION_OPERATOR,
    DIVISION_OPERATOR
]

EIB_VARIABLES = [
    "EIBAID"
    ,"EIBCALEN"
    , "EIBDATE"
    , "IEBRCODE"
    , "EIBTASKN"
    , "EIBTIME"
    , "EIBTRMID"
    , "EIBTRNID"
]

SPECIAL_REGISTERS_VARIABLES = [
    "SORT-RETURN",
    "RETURN-CODE"
]

CYCLOMATIC_COMPLEXITY_VERBS = [
    SPACE + ALSO_KEYWORD,
    SPACE + ALTER_KEYWORD,
    SPACE + AND_KEYWORD,
    SPACE + DEPENDING_KEYWORD,
    SPACE + END_OF_PAGE_KEYWORD,
    SPACE + ENTRY_KEYWORD,
    SPACE + EOP_KEYWORD,
    SPACE + EXCEPTION_KEYWORD,
    SPACE + COBOL_VERB_EXIT,
    SPACE + COBOL_VERB_GOBACK,
    SPACE + COBOL_VERB_IF,
    SPACE + INVALID_KEYWORD,
    SPACE + OR_KEYWORD,
    SPACE + OVERFLOW_KEYWORD,
    SPACE + SIZE_KEYWORD,
    SPACE + STOP_KEYWORD,
    SPACE + TIMES_KEYWORD,
    SPACE + UNTIL_KEYWORD,
    SPACE + VARYING_KEYWORD,
    SPACE + COBOL_VERB_WHEN,
    SPACE + CICS_VERB_HANDLE,
    SPACE + CICS_VERB_LINK,
    SPACE + CICS_VERB_XCTL
]

P2C_TERMINATE = 'P2C-TERMINATE'

PYTHON_TO_COBOL_VERBS = [
    P2C_TERMINATE,
    ASSEMBLER_FAKE_VERB_GET_DD
]