
ATTRB_KEYWORD = "ATTRB"
BOTH_OPTION = "both"
CARRIAGE_RETURN = "\r"
CLOSE_PARENS = ")"
COBOL_COMMENT = "*"
COLON = ":"
COMMA = ","
COMMAND_PROMPT_PREFIX = "> "
CREATE_REGION = "create region"
CYCLE_DOWN = 1
CYCLE_UP = -1
DD_CONFIG_FILE = "dd.config"
DOWN_ARROW = 40
EMPTY_STRING = ""
ENTRY_CURSOR_COLOR = "green"
ENTER_KEY = "\r"
ENTRY_BOX_BACKGROUND = "white"
ENTRY_BOX_TEXT_COLOR = "black"
EQUALS = "="
ERROR_TEXT_COLOR = "red"
ESCAPE = 27
GENERIC_TRANS_ID = "XXXX"
HELP = "help"
HIDE_SYSOUT = "hide sysout"
INVALID_COMMAND_MSG = "INVALID COMMAND:"
LINE_SPACING = 6
LINUX_DOWN_ARROW = 116
LINUX_ENTER_KEY = 36
LINUX_ESCAPE_KEY = 9
LINUX_UP_ARROW = 111
LINUX_OS = "posix"
LIST_TRANSACTIONS = "list trans"
MAP_CONTINUATION_CHARACTER = "X"
MAP_FIELD_IDENTIFIER = 'DFHMDF'
NEWLINE = "\n"
OPEN_PARENS = "("
OS_LABEL = "OS: "
PIPE_FLAG = "<"
REGION_FILE_EXT = ".region"
SET_DD = "set dd"
SET_TRANSACTION = "set tran"
SHOW_SYSOUT = "show sysout"
SINGLE_QUOTE = "'"
SPACE = " "
STANDARD_BACKGROUND_COLOR = "black"
STANDARD_CURSOR_SIZE = 10
STANDARD_FONT = "Courier"
STANDARD_FONT_SIZE = 14
STANDARD_TEXT_COLOR = "white"
STANDARD_INFO_TEXT_COLOR = "light green"
START_COMMAND = "start"
SWITCH_REGION = "switch region"
SYSOUT_TITLE = "KRAIT SYSOUT Display"
SYSOUT_WINDOW_SIZE = '300x300+30+30'
TERMINAL_CONFIG = "terminal.config"
TRANSACTION_CONFIG_FILE = "trans.config"
UP_ARROW = 38
WINDOW_TITLE = "KRAIT CICS Emulator"
WINDOW_SIZE = '1520x768+2+2'
WINDOWS_OS = "nt"
ZERO = 0

EIB_NORMAL_RESP = 0
EIB_ITEM_ERR_RESP = 26
EIB_QIDERR_RESP = 44
EIB_NOT_AUTH_RESP = 70

ENTER_KEY = 13
ESCAPE_KEY = 27
F1_KEY = 112
F2_KEY = 113
F3_KEY = 114
F4_KEY = 115
F5_KEY = 116
F6_KEY = 117
F7_KEY = 118
F8_KEY = 119
F9_KEY = 120
F10_KEY = 121
F11_KEY = 122
F12_KEY = 123


ATTENTION_KEYS = [
    ENTER_KEY,
    ESCAPE_KEY,
    F1_KEY,
    F2_KEY,
    F3_KEY,
    F4_KEY,
    F5_KEY,
    F6_KEY,
    F7_KEY,
    F8_KEY,
    F9_KEY,
    F10_KEY,
    F11_KEY,
    F12_KEY
]

COMMAND_LIST = [
    [HELP, "Show Help Info"]
    , [SHOW_SYSOUT, "Open the SYSOUT Window"]
    , [HIDE_SYSOUT, "Close the SYSOUT Window"]
    , [LIST_TRANSACTIONS, "List transactions and corresponding programs"]
    , [SET_TRANSACTION, "Associate a transaction with a program"]
    , [SET_DD, "Associate a file with a DD entry"]
    , [CREATE_REGION, "Create a CICS Region"]
    , [SWITCH_REGION, "Switch to a CICS Region"]
]